/*
Delphix DCT API

Delphix DCT API

API version: 3.22.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the UpdateComplianceJobCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateComplianceJobCollectionResponse{}

// UpdateComplianceJobCollectionResponse struct for UpdateComplianceJobCollectionResponse
type UpdateComplianceJobCollectionResponse struct {
	Job *Job `json:"job,omitempty"`
}

// NewUpdateComplianceJobCollectionResponse instantiates a new UpdateComplianceJobCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateComplianceJobCollectionResponse() *UpdateComplianceJobCollectionResponse {
	this := UpdateComplianceJobCollectionResponse{}
	return &this
}

// NewUpdateComplianceJobCollectionResponseWithDefaults instantiates a new UpdateComplianceJobCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateComplianceJobCollectionResponseWithDefaults() *UpdateComplianceJobCollectionResponse {
	this := UpdateComplianceJobCollectionResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *UpdateComplianceJobCollectionResponse) GetJob() Job {
	if o == nil || IsNil(o.Job) {
		var ret Job
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateComplianceJobCollectionResponse) GetJobOk() (*Job, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *UpdateComplianceJobCollectionResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given Job and assigns it to the Job field.
func (o *UpdateComplianceJobCollectionResponse) SetJob(v Job) {
	o.Job = &v
}

func (o UpdateComplianceJobCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateComplianceJobCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableUpdateComplianceJobCollectionResponse struct {
	value *UpdateComplianceJobCollectionResponse
	isSet bool
}

func (v NullableUpdateComplianceJobCollectionResponse) Get() *UpdateComplianceJobCollectionResponse {
	return v.value
}

func (v *NullableUpdateComplianceJobCollectionResponse) Set(val *UpdateComplianceJobCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateComplianceJobCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateComplianceJobCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateComplianceJobCollectionResponse(val *UpdateComplianceJobCollectionResponse) *NullableUpdateComplianceJobCollectionResponse {
	return &NullableUpdateComplianceJobCollectionResponse{value: val, isSet: true}
}

func (v NullableUpdateComplianceJobCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateComplianceJobCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


