/*
Delphix DCT API

Delphix DCT API

API version: 3.25.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeDatabaseParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeDatabaseParameters{}

// UpgradeDatabaseParameters Parameters to upgrade a dSource/VDB.
type UpgradeDatabaseParameters struct {
	// The id of the dSource/VDB repository to upgrade to.
	RepositoryId string `json:"repository_id"`
	// Reference of the environment user to use for dSource/VDB upgrade.
	EnvironmentUserId *string `json:"environment_user_id,omitempty"`
	// The id of the SQL instance on the PPT environment that we want to use for pre-provisioning (MSSQL only).
	PptRepository *string `json:"ppt_repository,omitempty"`
}

type _UpgradeDatabaseParameters UpgradeDatabaseParameters

// NewUpgradeDatabaseParameters instantiates a new UpgradeDatabaseParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeDatabaseParameters(repositoryId string) *UpgradeDatabaseParameters {
	this := UpgradeDatabaseParameters{}
	this.RepositoryId = repositoryId
	return &this
}

// NewUpgradeDatabaseParametersWithDefaults instantiates a new UpgradeDatabaseParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeDatabaseParametersWithDefaults() *UpgradeDatabaseParameters {
	this := UpgradeDatabaseParameters{}
	return &this
}

// GetRepositoryId returns the RepositoryId field value
func (o *UpgradeDatabaseParameters) GetRepositoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value
// and a boolean to check if the value has been set.
func (o *UpgradeDatabaseParameters) GetRepositoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepositoryId, true
}

// SetRepositoryId sets field value
func (o *UpgradeDatabaseParameters) SetRepositoryId(v string) {
	o.RepositoryId = v
}

// GetEnvironmentUserId returns the EnvironmentUserId field value if set, zero value otherwise.
func (o *UpgradeDatabaseParameters) GetEnvironmentUserId() string {
	if o == nil || IsNil(o.EnvironmentUserId) {
		var ret string
		return ret
	}
	return *o.EnvironmentUserId
}

// GetEnvironmentUserIdOk returns a tuple with the EnvironmentUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeDatabaseParameters) GetEnvironmentUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentUserId) {
		return nil, false
	}
	return o.EnvironmentUserId, true
}

// HasEnvironmentUserId returns a boolean if a field has been set.
func (o *UpgradeDatabaseParameters) HasEnvironmentUserId() bool {
	if o != nil && !IsNil(o.EnvironmentUserId) {
		return true
	}

	return false
}

// SetEnvironmentUserId gets a reference to the given string and assigns it to the EnvironmentUserId field.
func (o *UpgradeDatabaseParameters) SetEnvironmentUserId(v string) {
	o.EnvironmentUserId = &v
}

// GetPptRepository returns the PptRepository field value if set, zero value otherwise.
func (o *UpgradeDatabaseParameters) GetPptRepository() string {
	if o == nil || IsNil(o.PptRepository) {
		var ret string
		return ret
	}
	return *o.PptRepository
}

// GetPptRepositoryOk returns a tuple with the PptRepository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeDatabaseParameters) GetPptRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.PptRepository) {
		return nil, false
	}
	return o.PptRepository, true
}

// HasPptRepository returns a boolean if a field has been set.
func (o *UpgradeDatabaseParameters) HasPptRepository() bool {
	if o != nil && !IsNil(o.PptRepository) {
		return true
	}

	return false
}

// SetPptRepository gets a reference to the given string and assigns it to the PptRepository field.
func (o *UpgradeDatabaseParameters) SetPptRepository(v string) {
	o.PptRepository = &v
}

func (o UpgradeDatabaseParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeDatabaseParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["repository_id"] = o.RepositoryId
	if !IsNil(o.EnvironmentUserId) {
		toSerialize["environment_user_id"] = o.EnvironmentUserId
	}
	if !IsNil(o.PptRepository) {
		toSerialize["ppt_repository"] = o.PptRepository
	}
	return toSerialize, nil
}

func (o *UpgradeDatabaseParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"repository_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeDatabaseParameters := _UpgradeDatabaseParameters{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeDatabaseParameters)

	if err != nil {
		return err
	}

	*o = UpgradeDatabaseParameters(varUpgradeDatabaseParameters)

	return err
}

type NullableUpgradeDatabaseParameters struct {
	value *UpgradeDatabaseParameters
	isSet bool
}

func (v NullableUpgradeDatabaseParameters) Get() *UpgradeDatabaseParameters {
	return v.value
}

func (v *NullableUpgradeDatabaseParameters) Set(val *UpgradeDatabaseParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeDatabaseParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeDatabaseParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeDatabaseParameters(val *UpgradeDatabaseParameters) *NullableUpgradeDatabaseParameters {
	return &NullableUpgradeDatabaseParameters{value: val, isSet: true}
}

func (v NullableUpgradeDatabaseParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeDatabaseParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


