/*
Delphix DCT API

Delphix DCT API

API version: 3.16.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the SearchNamespacesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchNamespacesResponse{}

// SearchNamespacesResponse struct for SearchNamespacesResponse
type SearchNamespacesResponse struct {
	Items []Namespace `json:"items,omitempty"`
	ResponseMetadata *PaginatedResponseMetadata `json:"response_metadata,omitempty"`
}

// NewSearchNamespacesResponse instantiates a new SearchNamespacesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchNamespacesResponse() *SearchNamespacesResponse {
	this := SearchNamespacesResponse{}
	return &this
}

// NewSearchNamespacesResponseWithDefaults instantiates a new SearchNamespacesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchNamespacesResponseWithDefaults() *SearchNamespacesResponse {
	this := SearchNamespacesResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SearchNamespacesResponse) GetItems() []Namespace {
	if o == nil || IsNil(o.Items) {
		var ret []Namespace
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchNamespacesResponse) GetItemsOk() ([]Namespace, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SearchNamespacesResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Namespace and assigns it to the Items field.
func (o *SearchNamespacesResponse) SetItems(v []Namespace) {
	o.Items = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *SearchNamespacesResponse) GetResponseMetadata() PaginatedResponseMetadata {
	if o == nil || IsNil(o.ResponseMetadata) {
		var ret PaginatedResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchNamespacesResponse) GetResponseMetadataOk() (*PaginatedResponseMetadata, bool) {
	if o == nil || IsNil(o.ResponseMetadata) {
		return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *SearchNamespacesResponse) HasResponseMetadata() bool {
	if o != nil && !IsNil(o.ResponseMetadata) {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given PaginatedResponseMetadata and assigns it to the ResponseMetadata field.
func (o *SearchNamespacesResponse) SetResponseMetadata(v PaginatedResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o SearchNamespacesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchNamespacesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.ResponseMetadata) {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return toSerialize, nil
}

type NullableSearchNamespacesResponse struct {
	value *SearchNamespacesResponse
	isSet bool
}

func (v NullableSearchNamespacesResponse) Get() *SearchNamespacesResponse {
	return v.value
}

func (v *NullableSearchNamespacesResponse) Set(val *SearchNamespacesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchNamespacesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchNamespacesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchNamespacesResponse(val *SearchNamespacesResponse) *NullableSearchNamespacesResponse {
	return &NullableSearchNamespacesResponse{value: val, isSet: true}
}

func (v NullableSearchNamespacesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchNamespacesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


