/*
Delphix DCT API

Delphix DCT API

API version: 3.25.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the ExecutePaaSDatabaseComplianceJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutePaaSDatabaseComplianceJobResponse{}

// ExecutePaaSDatabaseComplianceJobResponse struct for ExecutePaaSDatabaseComplianceJobResponse
type ExecutePaaSDatabaseComplianceJobResponse struct {
	Job *Job `json:"job,omitempty"`
}

// NewExecutePaaSDatabaseComplianceJobResponse instantiates a new ExecutePaaSDatabaseComplianceJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutePaaSDatabaseComplianceJobResponse() *ExecutePaaSDatabaseComplianceJobResponse {
	this := ExecutePaaSDatabaseComplianceJobResponse{}
	return &this
}

// NewExecutePaaSDatabaseComplianceJobResponseWithDefaults instantiates a new ExecutePaaSDatabaseComplianceJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutePaaSDatabaseComplianceJobResponseWithDefaults() *ExecutePaaSDatabaseComplianceJobResponse {
	this := ExecutePaaSDatabaseComplianceJobResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *ExecutePaaSDatabaseComplianceJobResponse) GetJob() Job {
	if o == nil || IsNil(o.Job) {
		var ret Job
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutePaaSDatabaseComplianceJobResponse) GetJobOk() (*Job, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *ExecutePaaSDatabaseComplianceJobResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given Job and assigns it to the Job field.
func (o *ExecutePaaSDatabaseComplianceJobResponse) SetJob(v Job) {
	o.Job = &v
}

func (o ExecutePaaSDatabaseComplianceJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutePaaSDatabaseComplianceJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableExecutePaaSDatabaseComplianceJobResponse struct {
	value *ExecutePaaSDatabaseComplianceJobResponse
	isSet bool
}

func (v NullableExecutePaaSDatabaseComplianceJobResponse) Get() *ExecutePaaSDatabaseComplianceJobResponse {
	return v.value
}

func (v *NullableExecutePaaSDatabaseComplianceJobResponse) Set(val *ExecutePaaSDatabaseComplianceJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutePaaSDatabaseComplianceJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutePaaSDatabaseComplianceJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutePaaSDatabaseComplianceJobResponse(val *ExecutePaaSDatabaseComplianceJobResponse) *NullableExecutePaaSDatabaseComplianceJobResponse {
	return &NullableExecutePaaSDatabaseComplianceJobResponse{value: val, isSet: true}
}

func (v NullableExecutePaaSDatabaseComplianceJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutePaaSDatabaseComplianceJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


