/*
Delphix DCT API

Delphix DCT API

API version: 3.18.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the ExecutionComponentsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionComponentsListResponse{}

// ExecutionComponentsListResponse struct for ExecutionComponentsListResponse
type ExecutionComponentsListResponse struct {
	Items []ExecutionComponent `json:"items,omitempty"`
	ResponseMetadata *PaginatedResponseMetadata `json:"response_metadata,omitempty"`
}

// NewExecutionComponentsListResponse instantiates a new ExecutionComponentsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionComponentsListResponse() *ExecutionComponentsListResponse {
	this := ExecutionComponentsListResponse{}
	return &this
}

// NewExecutionComponentsListResponseWithDefaults instantiates a new ExecutionComponentsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionComponentsListResponseWithDefaults() *ExecutionComponentsListResponse {
	this := ExecutionComponentsListResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ExecutionComponentsListResponse) GetItems() []ExecutionComponent {
	if o == nil || IsNil(o.Items) {
		var ret []ExecutionComponent
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionComponentsListResponse) GetItemsOk() ([]ExecutionComponent, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ExecutionComponentsListResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ExecutionComponent and assigns it to the Items field.
func (o *ExecutionComponentsListResponse) SetItems(v []ExecutionComponent) {
	o.Items = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *ExecutionComponentsListResponse) GetResponseMetadata() PaginatedResponseMetadata {
	if o == nil || IsNil(o.ResponseMetadata) {
		var ret PaginatedResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionComponentsListResponse) GetResponseMetadataOk() (*PaginatedResponseMetadata, bool) {
	if o == nil || IsNil(o.ResponseMetadata) {
		return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *ExecutionComponentsListResponse) HasResponseMetadata() bool {
	if o != nil && !IsNil(o.ResponseMetadata) {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given PaginatedResponseMetadata and assigns it to the ResponseMetadata field.
func (o *ExecutionComponentsListResponse) SetResponseMetadata(v PaginatedResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o ExecutionComponentsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionComponentsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.ResponseMetadata) {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return toSerialize, nil
}

type NullableExecutionComponentsListResponse struct {
	value *ExecutionComponentsListResponse
	isSet bool
}

func (v NullableExecutionComponentsListResponse) Get() *ExecutionComponentsListResponse {
	return v.value
}

func (v *NullableExecutionComponentsListResponse) Set(val *ExecutionComponentsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionComponentsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionComponentsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionComponentsListResponse(val *ExecutionComponentsListResponse) *NullableExecutionComponentsListResponse {
	return &NullableExecutionComponentsListResponse{value: val, isSet: true}
}

func (v NullableExecutionComponentsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionComponentsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


