/*
Delphix DCT API

Delphix DCT API

API version: 3.20.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppDataSourceCreateParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDataSourceCreateParameters{}

// AppDataSourceCreateParameters struct for AppDataSourceCreateParameters
type AppDataSourceCreateParameters struct {
	// The type of source to create. Default is DIRECT.
	Type string `json:"type"`
	// The name of the source.
	Name string `json:"name"`
	// The ID of the Repository onto which the source will be created.
	RepositoryId string `json:"repository_id"`
	// Whether this source should be used for linking.
	LinkingEnabled *bool `json:"linking_enabled,omitempty"`
	// The environment user reference.
	EnvironmentUser *string `json:"environment_user,omitempty"`
	// The JSON payload conforming to the DraftV4 schema based on the type of application data being manipulated.
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// The path to the data to be synced. This should only be passed for type=DIRECT.
	Path *string `json:"path,omitempty"`
	// The ID of the environment to create the source on.
	EnvironmentId *string `json:"environment_id,omitempty"`
	// The ID of the engine to create the source on.
	EngineId *string `json:"engine_id,omitempty"`
}

type _AppDataSourceCreateParameters AppDataSourceCreateParameters

// NewAppDataSourceCreateParameters instantiates a new AppDataSourceCreateParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDataSourceCreateParameters(type_ string, name string, repositoryId string) *AppDataSourceCreateParameters {
	this := AppDataSourceCreateParameters{}
	this.Type = type_
	this.Name = name
	this.RepositoryId = repositoryId
	var linkingEnabled bool = true
	this.LinkingEnabled = &linkingEnabled
	return &this
}

// NewAppDataSourceCreateParametersWithDefaults instantiates a new AppDataSourceCreateParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDataSourceCreateParametersWithDefaults() *AppDataSourceCreateParameters {
	this := AppDataSourceCreateParameters{}
	var type_ string = "DIRECT"
	this.Type = type_
	var linkingEnabled bool = true
	this.LinkingEnabled = &linkingEnabled
	return &this
}

// GetType returns the Type field value
func (o *AppDataSourceCreateParameters) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppDataSourceCreateParameters) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AppDataSourceCreateParameters) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppDataSourceCreateParameters) SetName(v string) {
	o.Name = v
}

// GetRepositoryId returns the RepositoryId field value
func (o *AppDataSourceCreateParameters) GetRepositoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetRepositoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepositoryId, true
}

// SetRepositoryId sets field value
func (o *AppDataSourceCreateParameters) SetRepositoryId(v string) {
	o.RepositoryId = v
}

// GetLinkingEnabled returns the LinkingEnabled field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetLinkingEnabled() bool {
	if o == nil || IsNil(o.LinkingEnabled) {
		var ret bool
		return ret
	}
	return *o.LinkingEnabled
}

// GetLinkingEnabledOk returns a tuple with the LinkingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetLinkingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.LinkingEnabled) {
		return nil, false
	}
	return o.LinkingEnabled, true
}

// HasLinkingEnabled returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasLinkingEnabled() bool {
	if o != nil && !IsNil(o.LinkingEnabled) {
		return true
	}

	return false
}

// SetLinkingEnabled gets a reference to the given bool and assigns it to the LinkingEnabled field.
func (o *AppDataSourceCreateParameters) SetLinkingEnabled(v bool) {
	o.LinkingEnabled = &v
}

// GetEnvironmentUser returns the EnvironmentUser field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetEnvironmentUser() string {
	if o == nil || IsNil(o.EnvironmentUser) {
		var ret string
		return ret
	}
	return *o.EnvironmentUser
}

// GetEnvironmentUserOk returns a tuple with the EnvironmentUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetEnvironmentUserOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentUser) {
		return nil, false
	}
	return o.EnvironmentUser, true
}

// HasEnvironmentUser returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasEnvironmentUser() bool {
	if o != nil && !IsNil(o.EnvironmentUser) {
		return true
	}

	return false
}

// SetEnvironmentUser gets a reference to the given string and assigns it to the EnvironmentUser field.
func (o *AppDataSourceCreateParameters) SetEnvironmentUser(v string) {
	o.EnvironmentUser = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *AppDataSourceCreateParameters) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *AppDataSourceCreateParameters) SetPath(v string) {
	o.Path = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetEnvironmentId() string {
	if o == nil || IsNil(o.EnvironmentId) {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentId) {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasEnvironmentId() bool {
	if o != nil && !IsNil(o.EnvironmentId) {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *AppDataSourceCreateParameters) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetEngineId returns the EngineId field value if set, zero value otherwise.
func (o *AppDataSourceCreateParameters) GetEngineId() string {
	if o == nil || IsNil(o.EngineId) {
		var ret string
		return ret
	}
	return *o.EngineId
}

// GetEngineIdOk returns a tuple with the EngineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDataSourceCreateParameters) GetEngineIdOk() (*string, bool) {
	if o == nil || IsNil(o.EngineId) {
		return nil, false
	}
	return o.EngineId, true
}

// HasEngineId returns a boolean if a field has been set.
func (o *AppDataSourceCreateParameters) HasEngineId() bool {
	if o != nil && !IsNil(o.EngineId) {
		return true
	}

	return false
}

// SetEngineId gets a reference to the given string and assigns it to the EngineId field.
func (o *AppDataSourceCreateParameters) SetEngineId(v string) {
	o.EngineId = &v
}

func (o AppDataSourceCreateParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDataSourceCreateParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["repository_id"] = o.RepositoryId
	if !IsNil(o.LinkingEnabled) {
		toSerialize["linking_enabled"] = o.LinkingEnabled
	}
	if !IsNil(o.EnvironmentUser) {
		toSerialize["environment_user"] = o.EnvironmentUser
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.EnvironmentId) {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	if !IsNil(o.EngineId) {
		toSerialize["engine_id"] = o.EngineId
	}
	return toSerialize, nil
}

func (o *AppDataSourceCreateParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"repository_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppDataSourceCreateParameters := _AppDataSourceCreateParameters{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppDataSourceCreateParameters)

	if err != nil {
		return err
	}

	*o = AppDataSourceCreateParameters(varAppDataSourceCreateParameters)

	return err
}

type NullableAppDataSourceCreateParameters struct {
	value *AppDataSourceCreateParameters
	isSet bool
}

func (v NullableAppDataSourceCreateParameters) Get() *AppDataSourceCreateParameters {
	return v.value
}

func (v *NullableAppDataSourceCreateParameters) Set(val *AppDataSourceCreateParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDataSourceCreateParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDataSourceCreateParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDataSourceCreateParameters(val *AppDataSourceCreateParameters) *NullableAppDataSourceCreateParameters {
	return &NullableAppDataSourceCreateParameters{value: val, isSet: true}
}

func (v NullableAppDataSourceCreateParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDataSourceCreateParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


