/*
Delphix DCT API

Delphix DCT API

API version: 3.25.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FileMappingLocationParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileMappingLocationParameters{}

// FileMappingLocationParameters Parameters to validate file mapping using location.
type FileMappingLocationParameters struct {
	// The ID of the source object (dSource or VDB) to provision from.
	SourceDataId string `json:"source_data_id"`
	// The list of locations to use for source files to be mapped.
	Locations []string `json:"locations"`
	// File mapping rules for the VDB provisioning.
	FileMappingRules string `json:"file_mapping_rules"`
}

type _FileMappingLocationParameters FileMappingLocationParameters

// NewFileMappingLocationParameters instantiates a new FileMappingLocationParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileMappingLocationParameters(sourceDataId string, locations []string, fileMappingRules string) *FileMappingLocationParameters {
	this := FileMappingLocationParameters{}
	this.SourceDataId = sourceDataId
	this.Locations = locations
	this.FileMappingRules = fileMappingRules
	return &this
}

// NewFileMappingLocationParametersWithDefaults instantiates a new FileMappingLocationParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileMappingLocationParametersWithDefaults() *FileMappingLocationParameters {
	this := FileMappingLocationParameters{}
	return &this
}

// GetSourceDataId returns the SourceDataId field value
func (o *FileMappingLocationParameters) GetSourceDataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceDataId
}

// GetSourceDataIdOk returns a tuple with the SourceDataId field value
// and a boolean to check if the value has been set.
func (o *FileMappingLocationParameters) GetSourceDataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceDataId, true
}

// SetSourceDataId sets field value
func (o *FileMappingLocationParameters) SetSourceDataId(v string) {
	o.SourceDataId = v
}

// GetLocations returns the Locations field value
func (o *FileMappingLocationParameters) GetLocations() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value
// and a boolean to check if the value has been set.
func (o *FileMappingLocationParameters) GetLocationsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locations, true
}

// SetLocations sets field value
func (o *FileMappingLocationParameters) SetLocations(v []string) {
	o.Locations = v
}

// GetFileMappingRules returns the FileMappingRules field value
func (o *FileMappingLocationParameters) GetFileMappingRules() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileMappingRules
}

// GetFileMappingRulesOk returns a tuple with the FileMappingRules field value
// and a boolean to check if the value has been set.
func (o *FileMappingLocationParameters) GetFileMappingRulesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileMappingRules, true
}

// SetFileMappingRules sets field value
func (o *FileMappingLocationParameters) SetFileMappingRules(v string) {
	o.FileMappingRules = v
}

func (o FileMappingLocationParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileMappingLocationParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_data_id"] = o.SourceDataId
	toSerialize["locations"] = o.Locations
	toSerialize["file_mapping_rules"] = o.FileMappingRules
	return toSerialize, nil
}

func (o *FileMappingLocationParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_data_id",
		"locations",
		"file_mapping_rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileMappingLocationParameters := _FileMappingLocationParameters{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileMappingLocationParameters)

	if err != nil {
		return err
	}

	*o = FileMappingLocationParameters(varFileMappingLocationParameters)

	return err
}

type NullableFileMappingLocationParameters struct {
	value *FileMappingLocationParameters
	isSet bool
}

func (v NullableFileMappingLocationParameters) Get() *FileMappingLocationParameters {
	return v.value
}

func (v *NullableFileMappingLocationParameters) Set(val *FileMappingLocationParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableFileMappingLocationParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableFileMappingLocationParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileMappingLocationParameters(val *FileMappingLocationParameters) *NullableFileMappingLocationParameters {
	return &NullableFileMappingLocationParameters{value: val, isSet: true}
}

func (v NullableFileMappingLocationParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileMappingLocationParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


