/*
Delphix DCT API

Delphix DCT API

API version: 3.17.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PhoneHomeBundleApiTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhoneHomeBundleApiTelemetry{}

// PhoneHomeBundleApiTelemetry Telemetry data for an HTTP API call.
type PhoneHomeBundleApiTelemetry struct {
	// A programmatically-generated and auto-incrementing ID number for the API call.
	Id NullableInt64 `json:"id"`
	// The API endpoint path that was called. Note that all identifiable parameters are removed.
	ApiEndpoint string `json:"api_endpoint"`
	// The HTTP method used to call the API endpoint.
	ApiMethod string `json:"api_method"`
	// The UTC time the API call was initiated (ISO 8601 format).
	StartTime string `json:"start_time"`
	// The UTC time the API call returned a response (ISO 8601 format).
	EndTime string `json:"end_time"`
	// The HTTP status code of the response.
	ResponseStatus int32 `json:"response_status"`
	// The value of the \"User-Agent\" header in the request, if present.
	UserAgent string `json:"user_agent"`
	// The Data Control Tower client name (X-Dct-Client-Name HTTP header). This is used by Delphix-built integrations, like the Terraform Provider.
	ClientName string `json:"client_name"`
	// True if the API is classified as an automation API which is the basis of how API calls are charged.
	IsAutomation bool `json:"is_automation"`
	// The version of this Data Control Tower instance at the time the API was called.
	DctVersion string `json:"dct_version"`
	// A number to identify the user account or API key that performed this API call.
	AccountId int64 `json:"account_id"`
}

type _PhoneHomeBundleApiTelemetry PhoneHomeBundleApiTelemetry

// NewPhoneHomeBundleApiTelemetry instantiates a new PhoneHomeBundleApiTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhoneHomeBundleApiTelemetry(id NullableInt64, apiEndpoint string, apiMethod string, startTime string, endTime string, responseStatus int32, userAgent string, clientName string, isAutomation bool, dctVersion string, accountId int64) *PhoneHomeBundleApiTelemetry {
	this := PhoneHomeBundleApiTelemetry{}
	this.Id = id
	this.ApiEndpoint = apiEndpoint
	this.ApiMethod = apiMethod
	this.StartTime = startTime
	this.EndTime = endTime
	this.ResponseStatus = responseStatus
	this.UserAgent = userAgent
	this.ClientName = clientName
	this.IsAutomation = isAutomation
	this.DctVersion = dctVersion
	this.AccountId = accountId
	return &this
}

// NewPhoneHomeBundleApiTelemetryWithDefaults instantiates a new PhoneHomeBundleApiTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhoneHomeBundleApiTelemetryWithDefaults() *PhoneHomeBundleApiTelemetry {
	this := PhoneHomeBundleApiTelemetry{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *PhoneHomeBundleApiTelemetry) GetId() int64 {
	if o == nil || o.Id.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PhoneHomeBundleApiTelemetry) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *PhoneHomeBundleApiTelemetry) SetId(v int64) {
	o.Id.Set(&v)
}

// GetApiEndpoint returns the ApiEndpoint field value
func (o *PhoneHomeBundleApiTelemetry) GetApiEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiEndpoint
}

// GetApiEndpointOk returns a tuple with the ApiEndpoint field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetApiEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiEndpoint, true
}

// SetApiEndpoint sets field value
func (o *PhoneHomeBundleApiTelemetry) SetApiEndpoint(v string) {
	o.ApiEndpoint = v
}

// GetApiMethod returns the ApiMethod field value
func (o *PhoneHomeBundleApiTelemetry) GetApiMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiMethod
}

// GetApiMethodOk returns a tuple with the ApiMethod field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetApiMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiMethod, true
}

// SetApiMethod sets field value
func (o *PhoneHomeBundleApiTelemetry) SetApiMethod(v string) {
	o.ApiMethod = v
}

// GetStartTime returns the StartTime field value
func (o *PhoneHomeBundleApiTelemetry) GetStartTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetStartTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *PhoneHomeBundleApiTelemetry) SetStartTime(v string) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *PhoneHomeBundleApiTelemetry) GetEndTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetEndTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *PhoneHomeBundleApiTelemetry) SetEndTime(v string) {
	o.EndTime = v
}

// GetResponseStatus returns the ResponseStatus field value
func (o *PhoneHomeBundleApiTelemetry) GetResponseStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetResponseStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseStatus, true
}

// SetResponseStatus sets field value
func (o *PhoneHomeBundleApiTelemetry) SetResponseStatus(v int32) {
	o.ResponseStatus = v
}

// GetUserAgent returns the UserAgent field value
func (o *PhoneHomeBundleApiTelemetry) GetUserAgent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *PhoneHomeBundleApiTelemetry) SetUserAgent(v string) {
	o.UserAgent = v
}

// GetClientName returns the ClientName field value
func (o *PhoneHomeBundleApiTelemetry) GetClientName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientName
}

// GetClientNameOk returns a tuple with the ClientName field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetClientNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientName, true
}

// SetClientName sets field value
func (o *PhoneHomeBundleApiTelemetry) SetClientName(v string) {
	o.ClientName = v
}

// GetIsAutomation returns the IsAutomation field value
func (o *PhoneHomeBundleApiTelemetry) GetIsAutomation() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAutomation
}

// GetIsAutomationOk returns a tuple with the IsAutomation field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetIsAutomationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAutomation, true
}

// SetIsAutomation sets field value
func (o *PhoneHomeBundleApiTelemetry) SetIsAutomation(v bool) {
	o.IsAutomation = v
}

// GetDctVersion returns the DctVersion field value
func (o *PhoneHomeBundleApiTelemetry) GetDctVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DctVersion
}

// GetDctVersionOk returns a tuple with the DctVersion field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetDctVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DctVersion, true
}

// SetDctVersion sets field value
func (o *PhoneHomeBundleApiTelemetry) SetDctVersion(v string) {
	o.DctVersion = v
}

// GetAccountId returns the AccountId field value
func (o *PhoneHomeBundleApiTelemetry) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *PhoneHomeBundleApiTelemetry) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *PhoneHomeBundleApiTelemetry) SetAccountId(v int64) {
	o.AccountId = v
}

func (o PhoneHomeBundleApiTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhoneHomeBundleApiTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["api_endpoint"] = o.ApiEndpoint
	toSerialize["api_method"] = o.ApiMethod
	toSerialize["start_time"] = o.StartTime
	toSerialize["end_time"] = o.EndTime
	toSerialize["response_status"] = o.ResponseStatus
	toSerialize["user_agent"] = o.UserAgent
	toSerialize["client_name"] = o.ClientName
	toSerialize["is_automation"] = o.IsAutomation
	toSerialize["dct_version"] = o.DctVersion
	toSerialize["account_id"] = o.AccountId
	return toSerialize, nil
}

func (o *PhoneHomeBundleApiTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"api_endpoint",
		"api_method",
		"start_time",
		"end_time",
		"response_status",
		"user_agent",
		"client_name",
		"is_automation",
		"dct_version",
		"account_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPhoneHomeBundleApiTelemetry := _PhoneHomeBundleApiTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPhoneHomeBundleApiTelemetry)

	if err != nil {
		return err
	}

	*o = PhoneHomeBundleApiTelemetry(varPhoneHomeBundleApiTelemetry)

	return err
}

type NullablePhoneHomeBundleApiTelemetry struct {
	value *PhoneHomeBundleApiTelemetry
	isSet bool
}

func (v NullablePhoneHomeBundleApiTelemetry) Get() *PhoneHomeBundleApiTelemetry {
	return v.value
}

func (v *NullablePhoneHomeBundleApiTelemetry) Set(val *PhoneHomeBundleApiTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullablePhoneHomeBundleApiTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullablePhoneHomeBundleApiTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhoneHomeBundleApiTelemetry(val *PhoneHomeBundleApiTelemetry) *NullablePhoneHomeBundleApiTelemetry {
	return &NullablePhoneHomeBundleApiTelemetry{value: val, isSet: true}
}

func (v NullablePhoneHomeBundleApiTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhoneHomeBundleApiTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


