/*
Delphix DCT API

Delphix DCT API

API version: 3.23.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the SearchTagsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchTagsResponse{}

// SearchTagsResponse struct for SearchTagsResponse
type SearchTagsResponse struct {
	Items []GlobalTag `json:"items,omitempty"`
	ResponseMetadata *PaginatedResponseMetadata `json:"response_metadata,omitempty"`
}

// NewSearchTagsResponse instantiates a new SearchTagsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchTagsResponse() *SearchTagsResponse {
	this := SearchTagsResponse{}
	return &this
}

// NewSearchTagsResponseWithDefaults instantiates a new SearchTagsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchTagsResponseWithDefaults() *SearchTagsResponse {
	this := SearchTagsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SearchTagsResponse) GetItems() []GlobalTag {
	if o == nil || IsNil(o.Items) {
		var ret []GlobalTag
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTagsResponse) GetItemsOk() ([]GlobalTag, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SearchTagsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GlobalTag and assigns it to the Items field.
func (o *SearchTagsResponse) SetItems(v []GlobalTag) {
	o.Items = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *SearchTagsResponse) GetResponseMetadata() PaginatedResponseMetadata {
	if o == nil || IsNil(o.ResponseMetadata) {
		var ret PaginatedResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchTagsResponse) GetResponseMetadataOk() (*PaginatedResponseMetadata, bool) {
	if o == nil || IsNil(o.ResponseMetadata) {
		return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *SearchTagsResponse) HasResponseMetadata() bool {
	if o != nil && !IsNil(o.ResponseMetadata) {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given PaginatedResponseMetadata and assigns it to the ResponseMetadata field.
func (o *SearchTagsResponse) SetResponseMetadata(v PaginatedResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o SearchTagsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchTagsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.ResponseMetadata) {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return toSerialize, nil
}

type NullableSearchTagsResponse struct {
	value *SearchTagsResponse
	isSet bool
}

func (v NullableSearchTagsResponse) Get() *SearchTagsResponse {
	return v.value
}

func (v *NullableSearchTagsResponse) Set(val *SearchTagsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchTagsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchTagsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchTagsResponse(val *SearchTagsResponse) *NullableSearchTagsResponse {
	return &NullableSearchTagsResponse{value: val, isSet: true}
}

func (v NullableSearchTagsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchTagsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


