/*
Delphix DCT API

Delphix DCT API

API version: 3.18.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the UpgradeVDBResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeVDBResponse{}

// UpgradeVDBResponse struct for UpgradeVDBResponse
type UpgradeVDBResponse struct {
	Job *Job `json:"job,omitempty"`
}

// NewUpgradeVDBResponse instantiates a new UpgradeVDBResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeVDBResponse() *UpgradeVDBResponse {
	this := UpgradeVDBResponse{}
	return &this
}

// NewUpgradeVDBResponseWithDefaults instantiates a new UpgradeVDBResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeVDBResponseWithDefaults() *UpgradeVDBResponse {
	this := UpgradeVDBResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *UpgradeVDBResponse) GetJob() Job {
	if o == nil || IsNil(o.Job) {
		var ret Job
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeVDBResponse) GetJobOk() (*Job, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *UpgradeVDBResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given Job and assigns it to the Job field.
func (o *UpgradeVDBResponse) SetJob(v Job) {
	o.Job = &v
}

func (o UpgradeVDBResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeVDBResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableUpgradeVDBResponse struct {
	value *UpgradeVDBResponse
	isSet bool
}

func (v NullableUpgradeVDBResponse) Get() *UpgradeVDBResponse {
	return v.value
}

func (v *NullableUpgradeVDBResponse) Set(val *UpgradeVDBResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeVDBResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeVDBResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeVDBResponse(val *UpgradeVDBResponse) *NullableUpgradeVDBResponse {
	return &NullableUpgradeVDBResponse{value: val, isSet: true}
}

func (v NullableUpgradeVDBResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeVDBResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


