/*
Delphix DCT API

Delphix DCT API

API version: 3.1.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
	"time"
)

// checks if the ProvisionVDBByTimestampDefaultsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionVDBByTimestampDefaultsRequest{}

// ProvisionVDBByTimestampDefaultsRequest struct for ProvisionVDBByTimestampDefaultsRequest
type ProvisionVDBByTimestampDefaultsRequest struct {
	// The point in time from which to execute the operation. Mutually exclusive with timestamp_in_database_timezone. If the timestamp is not set, selects the latest point.
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// The point in time from which to execute the operation, expressed as a date-time in the timezone of the source database. Mutually exclusive with timestamp.
	TimestampInDatabaseTimezone *string `json:"timestamp_in_database_timezone,omitempty"`
	// The ID of the Engine onto which to provision. If the source ID unambiguously identifies a source object, this parameter is unnecessary and ignored.
	EngineId *string `json:"engine_id,omitempty"`
	// The ID of the source object (dSource or VDB) to provision from. All other objects referenced by the parameters must live on the same engine as the source.
	SourceDataId string `json:"source_data_id"`
}

// NewProvisionVDBByTimestampDefaultsRequest instantiates a new ProvisionVDBByTimestampDefaultsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionVDBByTimestampDefaultsRequest(sourceDataId string) *ProvisionVDBByTimestampDefaultsRequest {
	this := ProvisionVDBByTimestampDefaultsRequest{}
	this.SourceDataId = sourceDataId
	return &this
}

// NewProvisionVDBByTimestampDefaultsRequestWithDefaults instantiates a new ProvisionVDBByTimestampDefaultsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionVDBByTimestampDefaultsRequestWithDefaults() *ProvisionVDBByTimestampDefaultsRequest {
	this := ProvisionVDBByTimestampDefaultsRequest{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *ProvisionVDBByTimestampDefaultsRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetTimestampInDatabaseTimezone returns the TimestampInDatabaseTimezone field value if set, zero value otherwise.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetTimestampInDatabaseTimezone() string {
	if o == nil || IsNil(o.TimestampInDatabaseTimezone) {
		var ret string
		return ret
	}
	return *o.TimestampInDatabaseTimezone
}

// GetTimestampInDatabaseTimezoneOk returns a tuple with the TimestampInDatabaseTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetTimestampInDatabaseTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimestampInDatabaseTimezone) {
		return nil, false
	}
	return o.TimestampInDatabaseTimezone, true
}

// HasTimestampInDatabaseTimezone returns a boolean if a field has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) HasTimestampInDatabaseTimezone() bool {
	if o != nil && !IsNil(o.TimestampInDatabaseTimezone) {
		return true
	}

	return false
}

// SetTimestampInDatabaseTimezone gets a reference to the given string and assigns it to the TimestampInDatabaseTimezone field.
func (o *ProvisionVDBByTimestampDefaultsRequest) SetTimestampInDatabaseTimezone(v string) {
	o.TimestampInDatabaseTimezone = &v
}

// GetEngineId returns the EngineId field value if set, zero value otherwise.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetEngineId() string {
	if o == nil || IsNil(o.EngineId) {
		var ret string
		return ret
	}
	return *o.EngineId
}

// GetEngineIdOk returns a tuple with the EngineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetEngineIdOk() (*string, bool) {
	if o == nil || IsNil(o.EngineId) {
		return nil, false
	}
	return o.EngineId, true
}

// HasEngineId returns a boolean if a field has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) HasEngineId() bool {
	if o != nil && !IsNil(o.EngineId) {
		return true
	}

	return false
}

// SetEngineId gets a reference to the given string and assigns it to the EngineId field.
func (o *ProvisionVDBByTimestampDefaultsRequest) SetEngineId(v string) {
	o.EngineId = &v
}

// GetSourceDataId returns the SourceDataId field value
func (o *ProvisionVDBByTimestampDefaultsRequest) GetSourceDataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceDataId
}

// GetSourceDataIdOk returns a tuple with the SourceDataId field value
// and a boolean to check if the value has been set.
func (o *ProvisionVDBByTimestampDefaultsRequest) GetSourceDataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceDataId, true
}

// SetSourceDataId sets field value
func (o *ProvisionVDBByTimestampDefaultsRequest) SetSourceDataId(v string) {
	o.SourceDataId = v
}

func (o ProvisionVDBByTimestampDefaultsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionVDBByTimestampDefaultsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TimestampInDatabaseTimezone) {
		toSerialize["timestamp_in_database_timezone"] = o.TimestampInDatabaseTimezone
	}
	if !IsNil(o.EngineId) {
		toSerialize["engine_id"] = o.EngineId
	}
	toSerialize["source_data_id"] = o.SourceDataId
	return toSerialize, nil
}

type NullableProvisionVDBByTimestampDefaultsRequest struct {
	value *ProvisionVDBByTimestampDefaultsRequest
	isSet bool
}

func (v NullableProvisionVDBByTimestampDefaultsRequest) Get() *ProvisionVDBByTimestampDefaultsRequest {
	return v.value
}

func (v *NullableProvisionVDBByTimestampDefaultsRequest) Set(val *ProvisionVDBByTimestampDefaultsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionVDBByTimestampDefaultsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionVDBByTimestampDefaultsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionVDBByTimestampDefaultsRequest(val *ProvisionVDBByTimestampDefaultsRequest) *NullableProvisionVDBByTimestampDefaultsRequest {
	return &NullableProvisionVDBByTimestampDefaultsRequest{value: val, isSet: true}
}

func (v NullableProvisionVDBByTimestampDefaultsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionVDBByTimestampDefaultsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


