/*
Delphix DCT API

Delphix DCT API

API version: 3.25.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the ExportCleanupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportCleanupResponse{}

// ExportCleanupResponse struct for ExportCleanupResponse
type ExportCleanupResponse struct {
	Job *Job `json:"job,omitempty"`
}

// NewExportCleanupResponse instantiates a new ExportCleanupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportCleanupResponse() *ExportCleanupResponse {
	this := ExportCleanupResponse{}
	return &this
}

// NewExportCleanupResponseWithDefaults instantiates a new ExportCleanupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportCleanupResponseWithDefaults() *ExportCleanupResponse {
	this := ExportCleanupResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *ExportCleanupResponse) GetJob() Job {
	if o == nil || IsNil(o.Job) {
		var ret Job
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCleanupResponse) GetJobOk() (*Job, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *ExportCleanupResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given Job and assigns it to the Job field.
func (o *ExportCleanupResponse) SetJob(v Job) {
	o.Job = &v
}

func (o ExportCleanupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportCleanupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableExportCleanupResponse struct {
	value *ExportCleanupResponse
	isSet bool
}

func (v NullableExportCleanupResponse) Get() *ExportCleanupResponse {
	return v.value
}

func (v *NullableExportCleanupResponse) Set(val *ExportCleanupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExportCleanupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExportCleanupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportCleanupResponse(val *ExportCleanupResponse) *NullableExportCleanupResponse {
	return &NullableExportCleanupResponse{value: val, isSet: true}
}

func (v NullableExportCleanupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportCleanupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


