/*
Delphix DCT API

Delphix DCT API

API version: 3.23.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the ReassignSubConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReassignSubConnectionRequest{}

// ReassignSubConnectionRequest struct for ReassignSubConnectionRequest
type ReassignSubConnectionRequest struct {
	// The ID of the existing DataConnection to move the SubConnection to. If null, then a new DataConnection will be created.
	NewDataConnectionId *string `json:"new_data_connection_id,omitempty"`
	// The new DataConnection name. Only applicable if new_data_connection_id is null.
	Name *string `json:"name,omitempty"`
	// The tags to add to the newly created DataConnection. Only applicable if new_data_connection_id is null.
	Tags []Tag `json:"tags,omitempty"`
	// Whether the current Account must be configured as owner of the newly created DataConnection. Only applicable if new_data_connection_id is null.
	MakeCurrentAccountOwner *bool `json:"make_current_account_owner,omitempty"`
}

// NewReassignSubConnectionRequest instantiates a new ReassignSubConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReassignSubConnectionRequest() *ReassignSubConnectionRequest {
	this := ReassignSubConnectionRequest{}
	var makeCurrentAccountOwner bool = true
	this.MakeCurrentAccountOwner = &makeCurrentAccountOwner
	return &this
}

// NewReassignSubConnectionRequestWithDefaults instantiates a new ReassignSubConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReassignSubConnectionRequestWithDefaults() *ReassignSubConnectionRequest {
	this := ReassignSubConnectionRequest{}
	var makeCurrentAccountOwner bool = true
	this.MakeCurrentAccountOwner = &makeCurrentAccountOwner
	return &this
}

// GetNewDataConnectionId returns the NewDataConnectionId field value if set, zero value otherwise.
func (o *ReassignSubConnectionRequest) GetNewDataConnectionId() string {
	if o == nil || IsNil(o.NewDataConnectionId) {
		var ret string
		return ret
	}
	return *o.NewDataConnectionId
}

// GetNewDataConnectionIdOk returns a tuple with the NewDataConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReassignSubConnectionRequest) GetNewDataConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewDataConnectionId) {
		return nil, false
	}
	return o.NewDataConnectionId, true
}

// HasNewDataConnectionId returns a boolean if a field has been set.
func (o *ReassignSubConnectionRequest) HasNewDataConnectionId() bool {
	if o != nil && !IsNil(o.NewDataConnectionId) {
		return true
	}

	return false
}

// SetNewDataConnectionId gets a reference to the given string and assigns it to the NewDataConnectionId field.
func (o *ReassignSubConnectionRequest) SetNewDataConnectionId(v string) {
	o.NewDataConnectionId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReassignSubConnectionRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReassignSubConnectionRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReassignSubConnectionRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReassignSubConnectionRequest) SetName(v string) {
	o.Name = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ReassignSubConnectionRequest) GetTags() []Tag {
	if o == nil || IsNil(o.Tags) {
		var ret []Tag
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReassignSubConnectionRequest) GetTagsOk() ([]Tag, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ReassignSubConnectionRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []Tag and assigns it to the Tags field.
func (o *ReassignSubConnectionRequest) SetTags(v []Tag) {
	o.Tags = v
}

// GetMakeCurrentAccountOwner returns the MakeCurrentAccountOwner field value if set, zero value otherwise.
func (o *ReassignSubConnectionRequest) GetMakeCurrentAccountOwner() bool {
	if o == nil || IsNil(o.MakeCurrentAccountOwner) {
		var ret bool
		return ret
	}
	return *o.MakeCurrentAccountOwner
}

// GetMakeCurrentAccountOwnerOk returns a tuple with the MakeCurrentAccountOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReassignSubConnectionRequest) GetMakeCurrentAccountOwnerOk() (*bool, bool) {
	if o == nil || IsNil(o.MakeCurrentAccountOwner) {
		return nil, false
	}
	return o.MakeCurrentAccountOwner, true
}

// HasMakeCurrentAccountOwner returns a boolean if a field has been set.
func (o *ReassignSubConnectionRequest) HasMakeCurrentAccountOwner() bool {
	if o != nil && !IsNil(o.MakeCurrentAccountOwner) {
		return true
	}

	return false
}

// SetMakeCurrentAccountOwner gets a reference to the given bool and assigns it to the MakeCurrentAccountOwner field.
func (o *ReassignSubConnectionRequest) SetMakeCurrentAccountOwner(v bool) {
	o.MakeCurrentAccountOwner = &v
}

func (o ReassignSubConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReassignSubConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NewDataConnectionId) {
		toSerialize["new_data_connection_id"] = o.NewDataConnectionId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.MakeCurrentAccountOwner) {
		toSerialize["make_current_account_owner"] = o.MakeCurrentAccountOwner
	}
	return toSerialize, nil
}

type NullableReassignSubConnectionRequest struct {
	value *ReassignSubConnectionRequest
	isSet bool
}

func (v NullableReassignSubConnectionRequest) Get() *ReassignSubConnectionRequest {
	return v.value
}

func (v *NullableReassignSubConnectionRequest) Set(val *ReassignSubConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReassignSubConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReassignSubConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReassignSubConnectionRequest(val *ReassignSubConnectionRequest) *NullableReassignSubConnectionRequest {
	return &NullableReassignSubConnectionRequest{value: val, isSet: true}
}

func (v NullableReassignSubConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReassignSubConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


