/*
Delphix DCT API

Delphix DCT API

API version: 3.25.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the OracleActiveInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OracleActiveInstance{}

// OracleActiveInstance struct for OracleActiveInstance
type OracleActiveInstance struct {
	// The number of this instance.
	InstanceNumber *int32 `json:"instance_number,omitempty"`
	// The name of this instance.
	InstanceName *string `json:"instance_name,omitempty"`
	// The reference to the cluster node which the instance is running on.
	HostName *string `json:"host_name,omitempty"`
}

// NewOracleActiveInstance instantiates a new OracleActiveInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOracleActiveInstance() *OracleActiveInstance {
	this := OracleActiveInstance{}
	return &this
}

// NewOracleActiveInstanceWithDefaults instantiates a new OracleActiveInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOracleActiveInstanceWithDefaults() *OracleActiveInstance {
	this := OracleActiveInstance{}
	return &this
}

// GetInstanceNumber returns the InstanceNumber field value if set, zero value otherwise.
func (o *OracleActiveInstance) GetInstanceNumber() int32 {
	if o == nil || IsNil(o.InstanceNumber) {
		var ret int32
		return ret
	}
	return *o.InstanceNumber
}

// GetInstanceNumberOk returns a tuple with the InstanceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OracleActiveInstance) GetInstanceNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.InstanceNumber) {
		return nil, false
	}
	return o.InstanceNumber, true
}

// HasInstanceNumber returns a boolean if a field has been set.
func (o *OracleActiveInstance) HasInstanceNumber() bool {
	if o != nil && !IsNil(o.InstanceNumber) {
		return true
	}

	return false
}

// SetInstanceNumber gets a reference to the given int32 and assigns it to the InstanceNumber field.
func (o *OracleActiveInstance) SetInstanceNumber(v int32) {
	o.InstanceNumber = &v
}

// GetInstanceName returns the InstanceName field value if set, zero value otherwise.
func (o *OracleActiveInstance) GetInstanceName() string {
	if o == nil || IsNil(o.InstanceName) {
		var ret string
		return ret
	}
	return *o.InstanceName
}

// GetInstanceNameOk returns a tuple with the InstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OracleActiveInstance) GetInstanceNameOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceName) {
		return nil, false
	}
	return o.InstanceName, true
}

// HasInstanceName returns a boolean if a field has been set.
func (o *OracleActiveInstance) HasInstanceName() bool {
	if o != nil && !IsNil(o.InstanceName) {
		return true
	}

	return false
}

// SetInstanceName gets a reference to the given string and assigns it to the InstanceName field.
func (o *OracleActiveInstance) SetInstanceName(v string) {
	o.InstanceName = &v
}

// GetHostName returns the HostName field value if set, zero value otherwise.
func (o *OracleActiveInstance) GetHostName() string {
	if o == nil || IsNil(o.HostName) {
		var ret string
		return ret
	}
	return *o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OracleActiveInstance) GetHostNameOk() (*string, bool) {
	if o == nil || IsNil(o.HostName) {
		return nil, false
	}
	return o.HostName, true
}

// HasHostName returns a boolean if a field has been set.
func (o *OracleActiveInstance) HasHostName() bool {
	if o != nil && !IsNil(o.HostName) {
		return true
	}

	return false
}

// SetHostName gets a reference to the given string and assigns it to the HostName field.
func (o *OracleActiveInstance) SetHostName(v string) {
	o.HostName = &v
}

func (o OracleActiveInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OracleActiveInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceNumber) {
		toSerialize["instance_number"] = o.InstanceNumber
	}
	if !IsNil(o.InstanceName) {
		toSerialize["instance_name"] = o.InstanceName
	}
	if !IsNil(o.HostName) {
		toSerialize["host_name"] = o.HostName
	}
	return toSerialize, nil
}

type NullableOracleActiveInstance struct {
	value *OracleActiveInstance
	isSet bool
}

func (v NullableOracleActiveInstance) Get() *OracleActiveInstance {
	return v.value
}

func (v *NullableOracleActiveInstance) Set(val *OracleActiveInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableOracleActiveInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableOracleActiveInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOracleActiveInstance(val *OracleActiveInstance) *NullableOracleActiveInstance {
	return &NullableOracleActiveInstance{value: val, isSet: true}
}

func (v NullableOracleActiveInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOracleActiveInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


