/*
Delphix DCT API

Delphix DCT API

API version: 3.9.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delphix_dct_api

import (
	"encoding/json"
)

// checks if the ListAlgorithmRevisionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAlgorithmRevisionsResponse{}

// ListAlgorithmRevisionsResponse struct for ListAlgorithmRevisionsResponse
type ListAlgorithmRevisionsResponse struct {
	Items []AlgorithmRevision `json:"items,omitempty"`
	ResponseMetadata *PaginatedResponseMetadata `json:"response_metadata,omitempty"`
}

// NewListAlgorithmRevisionsResponse instantiates a new ListAlgorithmRevisionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAlgorithmRevisionsResponse() *ListAlgorithmRevisionsResponse {
	this := ListAlgorithmRevisionsResponse{}
	return &this
}

// NewListAlgorithmRevisionsResponseWithDefaults instantiates a new ListAlgorithmRevisionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAlgorithmRevisionsResponseWithDefaults() *ListAlgorithmRevisionsResponse {
	this := ListAlgorithmRevisionsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListAlgorithmRevisionsResponse) GetItems() []AlgorithmRevision {
	if o == nil || IsNil(o.Items) {
		var ret []AlgorithmRevision
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlgorithmRevisionsResponse) GetItemsOk() ([]AlgorithmRevision, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListAlgorithmRevisionsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AlgorithmRevision and assigns it to the Items field.
func (o *ListAlgorithmRevisionsResponse) SetItems(v []AlgorithmRevision) {
	o.Items = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *ListAlgorithmRevisionsResponse) GetResponseMetadata() PaginatedResponseMetadata {
	if o == nil || IsNil(o.ResponseMetadata) {
		var ret PaginatedResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlgorithmRevisionsResponse) GetResponseMetadataOk() (*PaginatedResponseMetadata, bool) {
	if o == nil || IsNil(o.ResponseMetadata) {
		return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *ListAlgorithmRevisionsResponse) HasResponseMetadata() bool {
	if o != nil && !IsNil(o.ResponseMetadata) {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given PaginatedResponseMetadata and assigns it to the ResponseMetadata field.
func (o *ListAlgorithmRevisionsResponse) SetResponseMetadata(v PaginatedResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o ListAlgorithmRevisionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAlgorithmRevisionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.ResponseMetadata) {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return toSerialize, nil
}

type NullableListAlgorithmRevisionsResponse struct {
	value *ListAlgorithmRevisionsResponse
	isSet bool
}

func (v NullableListAlgorithmRevisionsResponse) Get() *ListAlgorithmRevisionsResponse {
	return v.value
}

func (v *NullableListAlgorithmRevisionsResponse) Set(val *ListAlgorithmRevisionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlgorithmRevisionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlgorithmRevisionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlgorithmRevisionsResponse(val *ListAlgorithmRevisionsResponse) *NullableListAlgorithmRevisionsResponse {
	return &NullableListAlgorithmRevisionsResponse{value: val, isSet: true}
}

func (v NullableListAlgorithmRevisionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlgorithmRevisionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


